#!/bin/bash

echo 'hi my name is jacktone owidi'
sleep 2 
echo 'am learning cloud computing "aws"'
sleep 2 
echo 'its really an experience'
sleep 2 
echo 'on my way to become a cloud engineer'
sleep 2 
echo 'everyone starts from someware'
sleep 2
echo 'help me GOD to achive this milestone'
sleep 2
echo 'thank you'
